# Generated by Django 4.0.4 on 2022-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('FW', 'Foot Wear'), ('AS', 'Accessories'), ('AL', 'Appliances')], max_length=2),
        ),
    ]
